### ISSUE TITLE
problem with Python3 , weewx 4.1.1

### ISSUE THREAD

**Issue by peters77** [morrowwm/weewxMQTT#2]
Hi,

there seems to be some Py2/Py3 incompatibility with the wxMesh driver. 

I got these error if I install it on Python3 and latest weewx 4.1.1 version:

`Jun 22 14:29:32 weewx weewx[10986] CRITICAL __main__: Caught unrecoverable exception:
Jun 22 14:29:32 weewx weewx[10986] CRITICAL __main__:     ****  invalid syntax (wxMesh.py, line 66)
Jun 22 14:29:32 weewx weewx[10986] CRITICAL __main__:     ****  Traceback (most recent call last):
Jun 22 14:29:32 weewx weewx[10986] CRITICAL __main__:     ****    File "/usr/share/weewx/weewxd", line 148, in main
Jun 22 14:29:32 weewx weewx[10986] CRITICAL __main__:     ****      engine = weewx.engine.StdEngine(config_dict)
Jun 22 14:29:32 weewx weewx[10986] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 69, in __init__
Jun 22 14:29:32 weewx weewx[10986] CRITICAL __main__:     ****      self.setupStation(config_dict)
Jun 22 14:29:32 weewx weewx[10986] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 92, in setupStation
Jun 22 14:29:32 weewx weewx[10986] CRITICAL __main__:     ****      __import__(driver)
Jun 22 14:29:32 weewx weewx[10986] CRITICAL __main__:     ****    File "/usr/share/weewx/user/wxMesh.py", line 66
Jun 22 14:29:32 weewx weewx[10986] CRITICAL __main__:     ****      except ValueError, e:
Jun 22 14:29:32 weewx weewx[10986] CRITICAL __main__:     ****                       ^
Jun 22 14:29:32 weewx weewx[10986] CRITICAL __main__:     ****  SyntaxError: invalid syntax
Jun 22 14:29:32 weewx weewx[10986] CRITICAL __main__:     ****  Exiting.`

Could you fix this!?

Regards,

Christian

**Comment by emogg** [comment]
Same problem for me. Pi OS, buster debian

**Comment by peters77** [comment]
emogg,

I switched to MQTTSubscribe (as a service, as driver possible too), works like a charm, even with Python 3 and weewx 4.
See:
https://groups.google.com/forum/#!searchin/weewx-user/wxmesh%7Csort:date/weewx-user/Uc7SG-yH7x0/266polPABQAJ

Regards,

Christian

**Comment by norecords** [comment]
I've made some changes to make it works with python 3 and weewx 4.1.1
#https://github.com/norecords/weewxMQTT/commit/ebb2905096ec74a8d690d33e87a4d7bb25f90f82

cheers.

**Comment by morrowwm** [comment]
Thank you, norecords. I merged in your changes and pushed them up as the main branch.

**Comment by norecords** [comment]
It's a pleasure, I'm using your driver for two years and I wanted to upgrade my weewx to the latest.

**Comment by morrowwm** [comment]
Closed, as the code merge fixed this issue with python 3

**Comment by morrowwm** [comment]
Closed, as the code merge fixed this issue with python 3
